maxmtu: '9216'
outdir: /data/scaleCalibration
preset: faster
quality: 17
site: SCALECALIB
storagethreads: 1
fps: 140
storeallframes: False
newfileinterval: 0
liveratio: 10
camera:
- name: visss_trigger
  serialnumber: S1145792
  follower: False
  interface: enp35s0f0
  ip: 192.168.100.2
  mac: 00:01:0D:C3:0F:34
  teledyneparameters:
    TestImageSelector: Off
    fastReadoutMode: Off
    ExposureMode: Timed
    ExposureTime: 200
    GainSelector: SensorAnalog
    Gain: 1
    BlackLevelRaw: 1
    TriggerMode: Off
    AcquisitionFrameRate: 140
    IO:
    - LineSelector: Line3
      outputLineSource: PulseOnStartofExposure
      outputLinePulseDuration: 60
      outputLinePulseDelay: 40
    - LineSelector: Line4
      outputLineSource: PulseOnStartofExposure
      outputLinePulseDuration: 30
      outputLinePulseDelay: 0
    sensorFpnCorrectionMode: Off
- name: visss_follower
  serialnumber: S1143155
  follower: True
  interface: enp35s0f1
  ip: 192.168.200.2
  mac: 00:01:0D:C3:04:9F
  teledyneparameters:
    TestImageSelector: Off
    fastReadoutMode: Off
    ExposureMode: Timed
    ExposureTime: 200
    GainSelector: SensorAnalog
    Gain: 1
    BlackLevelRaw: 1
    TriggerSelector: FrameStart
    TriggerMode: On
    TriggerSource: Line1
    sensorFpnCorrectionMode: Off
externalTrigger: []